# Generated by Django 4.2.3 on 2023-07-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_post_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
